name: weather_interview
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.3


dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  melos: ^3.1.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
